- name: Potential Duplicates
  # You may pin to the exact commit or the version.
  # uses: wow-actions/potential-duplicates@ea5de69f22f516228e198eb637e91580ab3bf398
  uses: wow-actions/potential-duplicates@v1.0.8
  with:
    # Your GitHub token for authentication.
    GITHUB_TOKEN: 
    # Filter issues by title.
    filter: # optional
    # Exclude keywords in title before detecting.
    exclude: # optional
    # Label to set, when potential duplicates are detected.
    label: # optional, default is potential-duplicate
    # Get issues with state to compare. Supported state: 'all', 'closed', 'open'
    state: # optional, default is all
    # Label color to set, when potential duplicates are detected.
    threshold: # optional, default is 0.6
    # Comment to post when potential duplicates are detected.
    comment: {{#issues}}
   [#{{ number }}] {{ title }} ({{ accuracy }}%)
   {{/issues}}
